from __future__ import annotations

from typing import Protocol

from src.datamodel.entities import (
    Account,
    Case,
    Contact,
    Contract,
    Document,
    Employee,
    Incident,
    Invoice,
    JiraIssue,
    Lead,
    Order,
    OrderItem,
    Opportunity,
    Page,
    Product,
)


class AccountRepository(Protocol):
    def get(self, id: str) -> Account | None: ...
    def save(self, entity: Account) -> None: ...
    def find_by(self, field: str, value: str) -> list[Account]: ...


class ContactRepository(Protocol):
    def get(self, id: str) -> Contact | None: ...
    def save(self, entity: Contact) -> None: ...
    def find_by(self, field: str, value: str) -> list[Contact]: ...


class OpportunityRepository(Protocol):
    def get(self, id: str) -> Opportunity | None: ...
    def save(self, entity: Opportunity) -> None: ...
    def find_by(self, field: str, value: str) -> list[Opportunity]: ...


class CaseRepository(Protocol):
    def get(self, id: str) -> Case | None: ...
    def save(self, entity: Case) -> None: ...
    def find_by(self, field: str, value: str) -> list[Case]: ...


class LeadRepository(Protocol):
    def get(self, id: str) -> Lead | None: ...
    def save(self, entity: Lead) -> None: ...
    def find_by(self, field: str, value: str) -> list[Lead]: ...


class OrderRepository(Protocol):
    def get(self, order_number: str) -> Order | None: ...
    def save(self, entity: Order) -> None: ...
    def find_by(self, field: str, value: str) -> list[Order]: ...


class OrderItemRepository(Protocol):
    def get(self, id: str) -> OrderItem | None: ...
    def save(self, entity: OrderItem) -> None: ...
    def find_by(self, field: str, value: str) -> list[OrderItem]: ...


class ProductRepository(Protocol):
    def get(self, material_number: str) -> Product | None: ...
    def save(self, entity: Product) -> None: ...
    def find_by(self, field: str, value: str) -> list[Product]: ...


class ContractRepository(Protocol):
    def get(self, id: str) -> Contract | None: ...
    def save(self, entity: Contract) -> None: ...
    def find_by(self, field: str, value: str) -> list[Contract]: ...


class InvoiceRepository(Protocol):
    def get(self, invoice_number: str) -> Invoice | None: ...
    def save(self, entity: Invoice) -> None: ...
    def find_by(self, field: str, value: str) -> list[Invoice]: ...


class IncidentRepository(Protocol):
    def get(self, number: str) -> Incident | None: ...
    def save(self, entity: Incident) -> None: ...
    def find_by(self, field: str, value: str) -> list[Incident]: ...


class EmployeeRepository(Protocol):
    def get(self, employee_id: str) -> Employee | None: ...
    def save(self, entity: Employee) -> None: ...
    def find_by(self, field: str, value: str) -> list[Employee]: ...


class PageRepository(Protocol):
    def get(self, page_id: str) -> Page | None: ...
    def save(self, entity: Page) -> None: ...
    def find_by(self, field: str, value: str) -> list[Page]: ...


class JiraIssueRepository(Protocol):
    def get(self, key: str) -> JiraIssue | None: ...
    def save(self, entity: JiraIssue) -> None: ...
    def find_by(self, field: str, value: str) -> list[JiraIssue]: ...


class DocumentRepository(Protocol):
    def get(self, id: str) -> Document | None: ...
    def save(self, entity: Document) -> None: ...
    def find_by(self, field: str, value: str) -> list[Document]: ...


class CanonicalStore(Protocol):
    """Unified store covering all entity repositories.

    Provides a generic interface for pipeline and shaper code that needs to
    resolve entities by name without importing per-entity repository types.
    """

    def get(self, entity: str, key: str) -> object | None: ...
    def save(self, entity: str, obj: object) -> None: ...
    def find_by(self, entity: str, field: str, value: str) -> list[object]: ...
