SAMPLE_PARAMS: dict[str, str] = {
    "id": "001",
    "sys_id": "abc123def456",
    "issue_key": "ABC-123",
    "space_key": "ENG",
    "page_id": "98765",
    "site_name": "HR",
    "workspace": "my-workspace",
    "report_id": "rpt-001",
    "workbook": "Sales",
    "view": "Overview",
    "env_id": "env-001",
    "app_id": "app-001",
    "appid": "app-001",
    "pagetype": "entityrecord",
    "sap-client": "100",
    "so": "12345",
    "_adf.ctrl-state": "state-xyz",
    "redirect": "n",
    "filter": "Region eq 'EMEA'",
    ":showVizHome": "no",
    "tenantId": "tenant-001",
    "screen": "Orders",
    "page": "1",
    "invoice_number": "INV-0001",
    "doc_id": "doc0001",
}
